### ISSUE TITLE
cryptic abort if php is not installed

### ISSUE THREAD

**Issue by obscurerichard** [hpbuniat/copy-paste-detector#1]
When run on a system that does not have php installed, copy-paste-detector will always abort in the following way:

```
$ node_modules/copy-paste-detector/bin/cpd  -i '*.js' -d /bin
copy-paste-detector 0.0.2 by Hans-Peter Buniat
[ copy-paste-detector ] SyntaxError: Unexpected token /
SyntaxError: Unexpected token /
  at Object.parse (native)
  at new ParsePHP (/var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/copy-paste-detector/lib/parser/php.js:30:32)
  at /var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/copy-paste-detector/lib/parser.js:31:26
  at forOwn (/var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/lodash/dist/lodash.js:2105:15)
  at Function.forEach (/var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/lodash/dist/lodash.js:3302:9)
  at new Parser (/var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/copy-paste-detector/lib/parser.js:29:9)
  at Object.<anonymous> (/var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/copy-paste-detector/lib/main.js:72:11)
  at Object.<anonymous> (/var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/copy-paste-detector/lib/main.js:106:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/var/lib/jenkins/jobs/create-integration-master/workspace/node_modules/copy-paste-detector/bin/cpd:2:1)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:124:16)
  at node.js:842:3
```

Digging deeper with `strace` I found that it was executing php and failing:

```
open("/tmp/shelljs_debdb65912d7d0c612e5", O_RDONLY) = 13
ioctl(13, FIOCLEX)                      = 0
fstat(13, {st_mode=S_IFREG|0664, st_size=27, ...}) = 0
read(13, "/bin/sh: 1: php: not found\n", 27) = 27
close(13)                               = 0
```

Installing PHP made copy-paste-detector work correctly.

**Comment by lemongao** [comment]
I also met such problem. But I don't know why PHP must been installed before run copy-paste-detector. I haven‘t see any depend about PHP on this link. https://www.npmjs.com/package/copy-paste-detector/v/0.0.2
