### ISSUE TITLE
Unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by ainthek** [hpbuniat/copy-paste-detector#4]
SyntaxError: Unexpected token ' in JSON at position 0
  at Object.parse (native)
  at new ParsePHP (C:\workspaces\node_modules\copy-paste-detector\lib\parser\php.js:32:32)
  at C:\workspaces\node_modules\copy-paste-detector\lib\parser.js:31:26
  at forOwn (C:\workspaces\node_modules\lodash\dist\lodash.js:2106:15)
  at Function.forEach (C:\workspaces\node_modules\lodash\dist\lodash.js:3303:9)
  at new Parser (C:\workspaces\node_modules\copy-paste-detector\lib\parser.js:29:9)
  at Object.<anonymous> (C:\workspaces\node_modules\copy-paste-detector\lib\main.js:72:11)
  at Object.<anonymous> (C:\workspaces\node_modules\copy-paste-detector\lib\main.js:106:4)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (C:\workspaces\node_modules\copy-paste-detector\bin\cpd:2:1)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

**Comment by petdance** [comment]
Looks like the same things as #1.

**Comment by petdance** [comment]
This also happens to me, but for me it's not that I don't PHP installed, but rather an older version of PHP that doesn't handle the `php -R "echo T_VARIABLE;"`.
